import os
from core.scanner import Scanner
# from agents.attacker import AttackerAgent
# from agents.patcher import PatcherAgent

def start_hunt(repo_url):
    # 1. Setup ephemeral workspace
    repo_name = repo_url.split("/")[-1]
    os.system(f"git clone {repo_url} ./workspaces/{repo_name}")
    
    # 2. Run Scanner
    scanner = Scanner(f"./workspaces/{repo_name}")
    vulnerabilities = scanner.run_semgrep()
    
    print(f"🔍 Found {len(vulnerabilities)} potential issues.")

    for vuln in vulnerabilities:
        severity = vuln['extra']['severity']
        file_path = vuln['path']
        
        # Inside your 'for vuln in vulnerabilities' loop in main.py:

        if severity == "ERROR" and is_valid:
            # 1. Prepare Workspace on GitHub
            repo_full_name = "OWASP/NodeGoat" # Example
            fork_repo, branch = gh_client.setup_workspace(repo_full_name)
            
            # 2. Get file content and patch it
            file_path = vuln['path']
            with open(f"./workspaces/{repo_name}/{file_path}", "r") as f:
                original_content = f.read()
            
            new_content = PatcherAgent.generate_fix(original_content, vuln['extra']['message'])
            
            # 3. Commit to the Fork
            fork_repo.update_file(
                path=file_path,
                message=f"Fixed {vuln['extra']['message']}",
                content=new_content,
                sha=fork_repo.get_contents(file_path, ref=branch).sha,
                branch=branch
            )
            
            # 4. Open the PR
            pr_url = gh_client.submit_pull_request(
                original_repo_full_name=repo_full_name,
                head_branch=branch,
                title=f"🛡️ Security Fix: {vuln['extra']['message']}",
                body="This PR was automatically generated by the Autonomous Bounty Hunter."
            )
            print(f"✅ PR Opened: {pr_url}")

if __name__ == "__main__":
    target = "https://github.com/OWASP/NodeGoat" # Example vulnerable repo
    start_hunt(target)